site:
  name: 'Deerfield Green'
  site: 'https://deerfieldgreen.com'
  base: '/'
  trailingSlash: false

metadata:
  title:
    default: 'Deerfield Green'
    template: '%s | Deerfield Green'
  description: 'Strategic consulting, quantitative investment, and purposeful philanthropy. Based in Tokyo and Atlanta.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 'Deerfield Green'
    type: website

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6
    post:
      isEnabled: true
      permalink: '/%slug%'
      robots:
        index: true
    list:
      isEnabled: true
      pathname: 'articles'
      robots:
        index: true
    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true
    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: true

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'light:only'
