name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Build Jekyll
        run: bundle exec jekyll build

      - name: Deploy preview
        uses: cloudflare/wrangler-action@v3
        id: deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --name deerfieldgreen-www-pr-${{ github.event.pull_request.number }}

      - name: Comment preview URL
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            **Preview deployed!**
            https://deerfieldgreen-www-pr-${{ github.event.pull_request.number }}.kevin-stoll.workers.dev
